# safelist
branches:
  only:
  - "master"
  - "develop"
  - "issue/68/CI"

os:
  - "linux"
  - "osx"

compiler:
  - "gcc"
  - "clang"

sudo: "require"

before_install:
  - "if [ \"$TRAVIS_OS_NAME\" = \"linux\" ]; then sudo apt-get update -qq; sudo apt-get install libx11-xcb1; fi"
  - "if [ \"$TRAVIS_OS_NAME\" = \"linux\" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi"
  - "if [ \"$TRAVIS_OS_NAME\" = \"osx\" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi"
  - "echo $PWD"
  - "git pull --all"

install:
  - "bash miniconda.sh -b -p $HOME/miniconda"
  - "export PATH=\"$HOME/miniconda/bin:$PATH\""
  - "hash -r"
  - "conda config --set always_yes yes --set changeps1 no"
  - "conda update -q conda"
  - "conda info -a"
  - "source $HOME/miniconda/etc/profile.d/conda.sh"
  - "export QT_QPA_PLATFORM='offscreen'"
  - "conda create -n p36 python=3.6"
  - "conda create -n p37 python=3.7"

script:
  - "conda activate p36"
  - "pip install -r PyDodo/requirements.txt"
  - "cd PyDodo/ && pytest -vs tests/ && cd -"
  # Test docker on Linux only as docker not yet supported on macOS within travis
  - "if [ \"$TRAVIS_OS_NAME\" = \"linux\" ]; then docker-compose up -d; sleep 20; docker-compose down; fi"
  # Run full integration tests
  - "if [ \"$TRAVIS_OS_NAME\" = \"linux\" ]; then docker-compose up -d; sleep 20; cd PyDodo/ && pytest -vs tests/ && cd - ; docker-compose down; fi"
  # Test on Python 3.7
  - "conda activate p37"
  - "pip install -r PyDodo/requirements.txt"
  - "cd PyDodo/ && pytest -vs tests/ && cd -"
  # Test docker on Linux only as docker not yet supported on macOS within travis
  - "if [ \"$TRAVIS_OS_NAME\" = \"linux\" ]; then docker-compose up -d; sleep 20; docker-compose down; fi"
  # Run full integration tests
  - "if [ \"$TRAVIS_OS_NAME\" = \"linux\" ]; then docker-compose up -d; sleep 20; cd PyDodo/ && pytest -vs tests/ && cd - ; docker-compose down; fi"
