default:
  host: "localhost"
  port: "5001"
  simulator: "bluesky"
  bluesky_simulator: "bluesky"
  college_simulator: "college"

  # Bluebird API endpoints (to be removed in favour of OpenAPI)
  status_code_aircraft_id_not_found: 404
  endpoint_load_scenario: "ic"
  endpoint_reset_simulation: "reset"
  endpoint_create_aircraft: "cre"
  endpoint_aircraft_position: "pos"
  endpoint_change_altitude: "alt"
  endpoint_change_speed: "spd"
  endpoint_change_vertical_speed: "vs"
  endpoint_change_heading: "hdg"


  # Physical
  feet_altitude_upper_limit: 6000
  flight_level_lower_limit: 60
