version: '3'

services:
  bluesky:
    container_name: bluesky
    image: turinginst/bluesky:latest
    expose:
      - 9000
      - 9001
  bluebird:
    container_name: bluebird
    depends_on:
      - bluesky
    image: turinginst/bluebird:latest
    ports:
      - 5001:5001
    environment:
      - BS_HOST=bluesky
